config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :medical_records, only: [:index, :new, :create, :destroy]
  resources :pets, only: [:new, :create] do
    get :medical_records, on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :pets, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :pet

  validates :patient_symptoms, :treatment, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  extend Enumerize

  enumerize :kind, in: [:dog, :cat]

  has_many :medical_records

  validates :name, :breed, :kind, presence: true
end

app/controllers/api/v1/pets_controller.rb
module Api
  module V1
    class PetsController < ApplicationController
      def index
        render jsonapi: pets,
               include: [:medical_records],
               status: :ok
      end

      private

      def pets
        @pets ||= Pet.all
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find params[:id]

    @medical_records = @pet.medical_records
  end
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_medical_record, only: [:destroy]

  def index
    @q = MedicalRecord.ransack(params[:q])
    @medical_records = @q.result(distinct: true)
  end

  def new
    @medical_record = MedicalRecord.new
  end

  def create
    @medical_record = MedicalRecord.new(medical_record_params)

    if @medical_record.save
      redirect_to new_medical_record_path, notice: t('.messages.success')
    else
      render :new
    end
  end

  def destroy
    @medical_record.destroy
    redirect_to medical_records_url, notice: t('.messages.success')
  end

  private

  def set_medical_record
    @medical_record = MedicalRecord.find(params[:id])
  end

  def medical_record_params
    params.require(:medical_record).permit(:pet_id, :patient_symptoms, :treatment)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to new_pet_path, notice: t('.create.messages.success')
    else
      render :new
    end
  end

  def medical_records
    @pet = Pet.find params[:pet_id]
    @medical_records = @pet.medical_records
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :birth_date, :breed, :kind)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% content_for(:action_human_name) do %>
  <%= t('.title') %>
<% end %>

<div class="card mb-4">
  <div class="card-block">
    <div class="table-responsive">
      <table class="table table-striped text-">
        <thead>
          <tr>
            <th class="text-primary"><%= Pet.human_attribute_name(:name) %></th>
            <th class="text-primary"><%= Pet.human_attribute_name(:birth_date) %></th>
            <th class="text-primary"><%= Pet.human_attribute_name(:breed) %></th>
            <th class="text-primary"><%= Pet.human_attribute_name(:kind) %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @pets.each do |pet| %>
            <tr>
              <td><%= pet.name %></td>
              <td><%= pet.birth_date && I18n.l(pet.birth_date) %></td>
              <td><%= pet.breed %></td>
              <td><%= pet.kind_text %></td>
              <td>
                <%= link_to medical_records_pets_path(pet_id: pet), title: 'Prontuários' do %>
                  <i class="fa fa-medkit margin-b-5 text-success" style="font-size: 22px"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <% if value.is_a?(String) %>
    <div class="alert <%= key == 'notice' ? 'bg-success' : 'bg-danger' %>" role="alert">
      <em class="fa fa-check-circle mr-2"></em>
      <%= raw(value) %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_sidebar_left.html.erb
<nav class="sidebar col-xs-12 col-sm-4 col-lg-3 col-xl-2">
  <h1 class="site-title"><a href="">
    Prontuário de Pets</a>
  </h1><br>

  <ul class="nav nav-pills flex-column sidebar-nav">
    <li class="nav-item">
      <%= link_to '/',
                  class: "nav-link #{current_page?('/') && 'active'}", title: 'Home' do %>
        <em class="fa fa-h-square"></em>ome</a>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to new_pet_path,
                  class: "nav-link #{current_page?(new_pet_path) && 'active'}" do %>
        <em class="fa fa-paw"></em>Criar Pet</a>
      <% end %>
    </li>

    <li class="nav-item">
      <%= link_to new_medical_record_path,
                  class: "nav-link #{current_page?(new_medical_record_path) && 'active'}" do %>
        <em class="fa fa-plus"></em>Prontuário</a>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to medical_records_path,
                  class: "nav-link #{current_page?(medical_records_path) && 'active'}" do %>
        <em class="fa fa-list"></em>Listar Prontuários</a>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet Records</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container-fluid" id="wrapper">
      <div class="row">
        <%= render 'layouts/sidebar_left' %>
        <main class="col-xs-12 col-sm-8 col-lg-9 col-xl-10 pt-3 pl-4 ml-auto">
          <header class="page-header">
            <% if flash.any? %>
              <section class="content-header">
                <%= render 'layouts/flash_messages' %>
              </section>
              <br>
            <% end %>
            <h3 class="text-black-50"><%= yield(:action_human_name) %></h3>
            <div class="clear"></div>
          </header>
          <section class="row">
            <div class="col-sm-12">
              <section class="row">
                <div class="col-md-12 col-lg-12">
                  <div id="modal-holder"></div>
                  <%= yield %>
                </div>
              </section>
            </div>
          </section>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/medical_records/_form.html.erb
<%= simple_form_for(@medical_record) do |f| %>
  <div class="col-11 no-padding ml-4">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group row mb-4">
          <div class="col-md-12">
            <%= f.association :pet, input_html: { class: 'form-control' } %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group row mb-4">
          <div class="col-md-12">
            <%= f.input :patient_symptoms, as: :string, input_html: { class: 'form-control' } %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="form-group row mb-4">
          <div class="col-md-12">
            <%= f.input :treatment, as: :string,
                        input_html: { class: 'form-control money' } %>
          </div>
        </div>
      </div>
    </div><br><br>
    <div class="box-footer">
      <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
      <%= link_to 'Voltar', pets_path, class: 'btn btn-warning' %>
    </div>
  </div>
<% end %>

app/views/medical_records/_search.html.erb
<%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group row mb-4">
        <div class="col-md-12">
          <%= f.select :pet_id_eq,
                       Pet.all.map{ |a| [a.name, a.id] }.to_a.insert(0, ['Todos Pets', 'all']),
                       {}, class: 'form-control select' %>
        </div>
      </div>
    </div>
    <div>
      <%= f.submit class: 'btn btn-primary btn-sm font-weight-bold' %>
    </div>
  </div>
  <br>
<% end %>

app/views/medical_records/index.html.erb
<% content_for(:action_human_name) do %>
  <%= t('.title') %>
<% end %>

<div class="card mb-4">
  <div class="card-block">
    <%= render 'search' %>

    <div class="table-responsive">
      <table class="table table-striped text-">
        <thead>
          <tr>
            <th class="text-primary"><%= MedicalRecord.human_attribute_name(:patient_symptoms) %></th>
            <th class="text-primary"><%= MedicalRecord.human_attribute_name(:treatment) %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @medical_records.each do |medical_record| %>
            <tr>
              <td><%= medical_record.patient_symptoms %></td>
              <td><%= medical_record.treatment %></td>
              <td>
                <%= link_to medical_record, method: :delete, data: { confirm: 'Tem certeza?' }, title: 'Apagar' do %>
                  <i class="fa fa-trash text-danger margin-b-5" style="font-size: 20px"></i>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/medical_records/new.html.erb
<% content_for(:action_human_name) do %>
  <%= t('.title') %>
<% end %>

<%= render 'form', medical_record: @medical_record %>

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
  <div class="col-11 no-padding ml-4">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group row mb-4">
          <div class="col-md-12">
            <%= f.input :name, input_html: { class: 'form-control' } %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group row mb-4">
          <div class="col-md-12">
            <%= f.input :birth_date, as: :string, input_html: { class: 'date form-control' } %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="form-group row mb-4">
          <div class="col-md-12">
            <%= f.input :breed, as: :string,
                        input_html: { class: 'form-control' } %>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group row mb-4">
          <div class="col-md-12">
            <%= f.input :kind, collection: Pet.kind.options,
                        input_html: { class: 'form-control' } %>
          </div>
        </div>
      </div>
    </div><br><br>
    <div class="actions">
      <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
      <%= link_to 'Voltar', pets_path, class: 'btn btn-warning' %>
    </div>
  </div>
<% end %>

app/views/pets/medical_records.html.erb
<% content_for(:action_human_name) do %>
  <%= t('.title', name: @pet.name) %>
<% end %>

<div class="row">
  <% @medical_records.each do |medical_record| %>
    <div class="col-md-6 mb-2">
      <div class="card">
        <div class="card-header">
          <%= MedicalRecord.human_attribute_name :id %>: <%= medical_record.id %>
        </div>
        <div class="card-body">
          <p>
            <strong><%= MedicalRecord.human_attribute_name :patient_symptoms %>:</strong>
            <%= medical_record.patient_symptoms %>
          </p>

          <p>
            <strong><%= MedicalRecord.human_attribute_name :treatment %>:</strong>
            <%= medical_record.treatment %>
          </p>
        </div>
        <br>
      </div>
    </div>
  <% end %>
</div><br>
<div class="actions">
  <%= link_to 'Voltar', '/', class: 'btn btn-warning' %>
</div>

app/views/pets/new.html.erb
<% content_for(:action_human_name) do %>
  <%= t('.title') %>
<% end %>
<%= render 'form', pet: @pet %>